name = "v2ray"
main = "src/worker.ts"
compatibility_date = "2024-05-29"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "settings", id = "a733bc91ea004a85af7b4de37fb4c7dd" }
]
